name: CI/CD Pipeline

on:
  push:
    branches: [ "main", "backend" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Скачивание кода
        uses: actions/checkout@v3

      - name: Установка .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Восстановление зависимостей
        run: dotnet restore backend/TrailsUA.Api/TrailsUA.Api.csproj

      - name: Сборка проекта
        run: dotnet build backend/TrailsUA.Api/TrailsUA.Api.csproj --configuration Release --no-restore

      - name: Запуск тестов
        run: dotnet test backend/TrailsUA.Api/TrailsUA.Api.csproj --no-build --verbosity normal

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /path/to/your/app
            git pull origin main
            dotnet publish backend/TrailsUA.Api/TrailsUA.Api.csproj -c Release -o out
            sudo systemctl restart trailsua
